default: &default
  store_options:
    max_size: 268435456  # 256 megabytes
    namespace: "rails_cache"

development:
  <<: *default

test:
  <<: *default

production:
  database: cache
  <<: *default
